# **실습을 위한 구글 코랩 설치**


*   **구글 코랩이란?**

구글이 제공하는 클라우드 기반 Jupyter Notebook 환경. 웹 브라우저에서 Python 코드를 작성하고 실행할 수 있음. 이 환경은 머신 러닝, 딥 러닝, 데이터 분석 등의 작업을 수행할 때 매우 유용

구글 코랩 소개 영상: https://www.youtube.com/watch?v=rNgswRZ2C1Y

구글 코랩 사용법: https://yeko90.tistory.com/entry/how-use-google-colab

# **실습 데이터 불러오기**

## **1. 데이터 불러오기 (자전거, 자궁암)**

In [1]:
# 구글 드라이브에 실습 파일을 넣고 불러오기
# from google.colab import drive
# drive.mount('/content/drive')

In [2]:
# 자전거, 자궁암 대여 데이터 불러오기

import pandas as pd

df_bike_raw = pd.read_csv(r"C:\001. Python\700. 설명가능인공지능_실습\bike.csv", engine = "python", encoding = "euc-kr")
df_bike = pd.read_csv(r"C:\001. Python\700. 설명가능인공지능_실습\bike-sharing-daily.csv", engine = "python", encoding = "euc-kr")


df_cancer = pd.read_csv(r"C:\001. Python\700. 설명가능인공지능_실습\cancer.csv", engine = "python", encoding = "euc-kr")


print(df_bike_raw.shape)
print(df_bike.shape)
print(df_cancer.shape)

(731, 12)
(731, 16)
(858, 16)

In [3]:
# 자전거 대여 raw 데이터 확인
df_bike_raw.head(10)
# x_bike: 자전거 대여량을 예측하기 위한 독립 변수(features)로, yr(연도), mnth(월), holiday(공휴일), 
# weekday(요일), workingday(근무일 여부), temp(온도), hum(습도), windspeed(풍속), 
# 그리고 계절(season_1 ~ season_4), 날씨(weathersit_1 ~ weathersit_3) 등을 포함함.
# y_bike: 예측할 종속 변수로, cnt(총 대여 수)를 선택.

,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,hum,windspeed,cnt,days_since_2011
0,WINTER,2011,JAN,NO HOLIDAY,SAT,NO WORKING DAY,MISTY,8.175849,80.5833,10.749882,985,0
1,WINTER,2011,JAN,NO HOLIDAY,SUN,NO WORKING DAY,MISTY,9.083466,69.6087,16.652113,801,1
2,WINTER,2011,JAN,NO HOLIDAY,MON,WORKING DAY,GOOD,1.229108,43.7273,16.636703,1349,2
3,WINTER,2011,JAN,NO HOLIDAY,TUE,WORKING DAY,GOOD,1.400000,59.0435,10.739832,1562,3
4,WINTER,2011,JAN,NO HOLIDAY,WED,WORKING DAY,GOOD,2.666979,43.6957,12.522300,1600,4
5,WINTER,2011,JAN,NO HOLIDAY,THU,WORKING DAY,GOOD,1.604356,51.8261,6.000868,1606,5
6,WINTER,2011,JAN,NO HOLIDAY,FRI,WORKING DAY,MISTY,1.236534,49.8696,11.304642,1510,6
7,WINTER,2011,JAN,NO HOLIDAY,SAT,NO WORKING DAY,MISTY,-0.245000,53.5833,17.875868,959,7
8,WINTER,2011,JAN,NO HOLIDAY,SUN,NO WORKING DAY,GOOD,-1.498349,43.4167,24.250650,822,8
9,WINTER,2011,JAN,NO HOLIDAY,MON,WORKING DAY,GOOD,-0.910849,48.2917,14.958889,1321,9

In [4]:
#자궁암 데이터 확인
df_cancer.head(10)

,Age,Number.of.sexual.partners,First.sexual.intercourse,Num.of.pregnancies,Smokes,Smokes..years.,Hormonal.Contraceptives,Hormonal.Contraceptives..years.,IUD,IUD..years.,STDs,STDs..number.,STDs..Number.of.diagnosis,STDs..Time.since.first.diagnosis,STDs..Time.since.last.diagnosis,Biopsy
0,18,4,15,1,0,0.000000,0,0.0,0,0.0,0,0,0,1,1,0
1,15,1,14,1,0,0.000000,0,0.0,0,0.0,0,0,0,1,1,0
2,34,1,15,1,0,0.000000,0,0.0,0,0.0,0,0,0,1,1,0
3,52,5,16,4,1,37.000000,1,3.0,0,0.0,0,0,0,1,1,0
4,46,3,21,4,0,0.000000,1,15.0,0,0.0,0,0,0,1,1,0
5,42,3,23,2,0,0.000000,0,0.0,0,0.0,0,0,0,1,1,0
6,51,3,17,6,1,34.000000,0,0.0,1,7.0,0,0,0,1,1,1
7,26,1,26,3,0,0.000000,1,2.0,1,7.0,0,0,0,1,1,0
8,45,1,20,5,0,0.000000,0,0.0,0,0.0,0,0,0,1,1,0
9,44,3,15,1,1,1.266973,0,0.0,0,0.0,0,0,0,1,1,0

## **2. 데이터 전처리**

컴퓨터는 데이터를 수치로 이해해서 범주형은 수치로 바꿔줘야 함. 추가로 스케일로 인한 예측 모델의 영향을 없애기 위해 정규화 (normalization)이 수치형 데이터에 필요.

대표적인 정규화 방법으로 주로 아래와 같은 Min-max scaling을 이용함.

![image.png]()

# **정규화 (Normalization) 공식 정리**

정규화(Normalization)는 데이터의 범위를 일정한 스케일로 변환하여 **분석, 머신러닝 모델 학습, 데이터 비교** 등을 용이하게 하는 기법입니다. 가장 일반적인 정규화 방법과 그 수식을 정리하면 다음과 같습니다.

---

## **1. Min-Max 정규화 (Min-Max Normalization)**
- 데이터 값을 **\[0,1\] 또는 \[-1,1\] 범위**로 변환하는 방법  
- 데이터의 상대적인 크기를 유지하면서 특정 범위로 조정할 때 사용  

```math
X_{\text{norm}} = \frac{X - X_{\min}}{X_{\max} - X_{\min}}
```

### **설명**
- \(X\): 원본 데이터 값  
- \(X_{\min}\): 데이터의 최소값  
- \(X_{\max}\): 데이터의 최대값  
- \(X_{\text{norm}}\): 정규화된 데이터 값 (0~1 범위)

### **예시**
| 원본 데이터 (\(X\)) | 최소값 (\(X_{\min}\)) | 최대값 (\(X_{\max}\)) | 정규화된 값 (\(X_{\text{norm}}\)) |
|------|------|------|------|
| 20 | 10 | 50 | \(\frac{20-10}{50-10} = 0.25\) |
| 30 | 10 | 50 | \(\frac{30-10}{50-10} = 0.5\) |
| 50 | 10 | 50 | \(\frac{50-10}{50-10} = 1.0\) |

---

## **2. Z-Score 정규화 (Standardization)**
- 데이터의 평균을 **0**, 표준 편차를 **1**로 맞추는 방법  
- 데이터의 분포를 유지하면서 표준 정규 분포(평균=0, 표준편차=1)로 변환할 때 사용  

```math
X_{\text{norm}} = \frac{X - \mu}{\sigma}
```

### **설명**
- \(X\): 원본 데이터 값  
- \(\mu\): 데이터의 평균  
- \(\sigma\): 데이터의 표준 편차  
- \(X_{\text{norm}}\): 정규화된 데이터 값 (평균 0, 표준 편차 1)

### **예시**
| 원본 데이터 (\(X\)) | 평균 (\(\mu\)) | 표준 편차 (\(\sigma\)) | 정규화된 값 (\(X_{\text{norm}}\)) |
|------|------|------|------|
| 20 | 30 | 10 | \(\frac{20-30}{10} = -1.0\) |
| 30 | 30 | 10 | \(\frac{30-30}{10} = 0.0\) |
| 40 | 30 | 10 | \(\frac{40-30}{10} = 1.0\) |

---

## **3. 최대 절댓값 정규화 (Max Abs Normalization)**
- 데이터의 최댓값을 기준으로 **-1에서 1 사이**로 변환  
- 음수 값이 포함된 경우에도 **원본 데이터의 방향성을 유지**할 때 유용  

```math
X_{\text{norm}} = \frac{X}{|X_{\max}|}
```

### **설명**
- \(X\): 원본 데이터 값  
- \(X_{\max}\): 데이터 절댓값 중 최대값  
- \(X_{\text{norm}}\): 정규화된 데이터 값 (-1~1 범위)

### **예시**
| 원본 데이터 (\(X\)) | 최대 절댓값 (\(|X_{\max}|\)) | 정규화된 값 (\(X_{\text{norm}}\)) |
|------|------|------|
| -50 | 100 | \(\frac{-50}{100} = -0.5\) |
| 25 | 100 | \(\frac{25}{100} = 0.25\) |
| 100 | 100 | \(\frac{100}{100} = 1.0\) |

---

## **4. 로그 정규화 (Log Normalization)**
- 데이터 값의 크기 차이가 클 때 **로그 변환**을 적용하여 분포를 조정  
- 특히 **지수적으로 증가하는 데이터**(예: 소득, 인구 수)에서 많이 사용  

```math
X_{\text{norm}} = \log(X + 1)
```

### **설명**
- \(X\): 원본 데이터 값  
- 로그 변환 시 0 이하의 값이 존재하면 +1을 더해 변환  
- 값이 클수록 상대적인 크기가 줄어들어 스케일 조정 효과 발생

### **예시**
| 원본 데이터 (\(X\)) | 정규화된 값 (\(X_{\text{norm}}\)) |
|------|------|
| 1 | \(\log(1+1) = 0.693\) |
| 10 | \(\log(10+1) = 2.398\) |
| 100 | \(\log(100+1) = 4.615\) |

---

## **5. 정규화 선택 기준**
| 정규화 방법 | 사용 상황 |
|------------|--------------------------------|
| **Min-Max 정규화** | 데이터 범위를 일정한 구간으로 변환할 때 |
| **Z-Score 정규화** | 평균과 표준 편차를 기준으로 정규화할 때 |
| **Max Abs 정규화** | 음수 데이터를 포함한 경우, 방향성을 유지할 때 |
| **로그 정규화** | 데이터의 분포가 기하급수적으로 증가할 때 |

---

## **결론**
- **정규화는 데이터의 크기를 조정하여 모델의 학습 성능을 높이고 비교를 용이하게 만듦**
- 어떤 정규화 방법을 선택할지는 **데이터의 분포와 특성**에 따라 달라짐
- 머신러닝에서 자주 사용되는 **Min-Max 정규화, Z-Score 정규화**를 주로 활용

🎯 **"데이터를 정규화하면 분석과 모델링이 훨씬 쉬워진다!"** 🚀

In [5]:
# 자전거 데이터에서 season은 1 (Winter), 2 (Spring), 3 (Summer), 4 (Fall)로 변환
# dteday는 year와 mnth로 나뉘어짐 (추후 연도와 달의 영향력 파악을 위해 split)
# Holiday, workingday 유무에 따라 0, 1로 변환
# temp, hum, windspped 수치형 이므로 min-max scaling을 이용해 0~1사이로 변환

df_bike.head(10)

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,2011-01-01,1,0,1,0,6,0,2,0.344167,0.363625,0.805833,0.160446,331,654,985
1,2,2011-01-02,1,0,1,0,0,0,2,0.363478,0.353739,0.696087,0.248539,131,670,801
2,3,2011-01-03,1,0,1,0,1,1,1,0.196364,0.189405,0.437273,0.248309,120,1229,1349
3,4,2011-01-04,1,0,1,0,2,1,1,0.200000,0.212122,0.590435,0.160296,108,1454,1562
4,5,2011-01-05,1,0,1,0,3,1,1,0.226957,0.229270,0.436957,0.186900,82,1518,1600
5,6,2011-01-06,1,0,1,0,4,1,1,0.204348,0.233209,0.518261,0.089565,88,1518,1606
6,7,2011-01-07,1,0,1,0,5,1,2,0.196522,0.208839,0.498696,0.168726,148,1362,1510
7,8,2011-01-08,1,0,1,0,6,0,2,0.165000,0.162254,0.535833,0.266804,68,891,959
8,9,2011-01-09,1,0,1,0,0,0,1,0.138333,0.116175,0.434167,0.361950,54,768,822
9,10,2011-01-10,1,0,1,0,1,1,1,0.150833,0.150888,0.482917,0.223267,41,1280,1321

## **3. 파이썬 Pandas를 이용하여 원하는 열 데이터 가져오기**

 Pandas library를 이용하여 원하는 열 데이터를 가져오는 방법에 대해서 배워봅시다.

In [6]:
print(df_bike['season'])

0      1
1      1
2      1
3      1
4      1
      ..
726    1
727    1
728    1
729    1
730    1
Name: season, Length: 731, dtype: int64

In [7]:
# 열 추출

print(df_bike['season'])
print(df_bike['temp'])

# 2개 이상 열 추출
print(df_bike[['season','temp']])

0      1
1      1
2      1
3      1
4      1
      ..
726    1
727    1
728    1
729    1
730    1
Name: season, Length: 731, dtype: int64
0      0.344167
1      0.363478
2      0.196364
3      0.200000
4      0.226957
         ...
726    0.254167
727    0.253333
728    0.253333
729    0.255833
730    0.215833
Name: temp, Length: 731, dtype: float64
     season      temp
0         1  0.344167
1         1  0.363478
2         1  0.196364
3         1  0.200000
4         1  0.226957
..      ...       ...
726       1  0.254167
727       1  0.253333
728       1  0.253333
729       1  0.255833
730       1  0.215833

[731 rows x 2 columns]

In [8]:
# 행 추출

print(df_bike.iloc[:10])

   instant      dteday  season  yr  mnth  holiday  weekday  workingday  \
0        1  2011-01-01       1   0     1        0        6           0
1        2  2011-01-02       1   0     1        0        0           0
2        3  2011-01-03       1   0     1        0        1           1
3        4  2011-01-04       1   0     1        0        2           1
4        5  2011-01-05       1   0     1        0        3           1
5        6  2011-01-06       1   0     1        0        4           1
6        7  2011-01-07       1   0     1        0        5           1
7        8  2011-01-08       1   0     1        0        6           0
8        9  2011-01-09       1   0     1        0        0           0
9       10  2011-01-10       1   0     1        0        1           1

   weathersit      temp     atemp       hum  windspeed  casual  registered  \
0           2  0.344167  0.363625  0.805833   0.160446     331         654
1           2  0.363478  0.353739  0.696087   0.248539     131         670
2           1  0.196364  0.189405  0.437273   0.248309     120        1229
3           1  0.200000  0.212122  0.590435   0.160296     108        1454
4           1  0.226957  0.229270  0.436957   0.186900      82        1518
5           1  0.204348  0.233209  0.518261   0.089565      88        1518
6           2  0.196522  0.208839  0.498696   0.168726     148        1362
7           2  0.165000  0.162254  0.535833   0.266804      68         891
8           1  0.138333  0.116175  0.434167   0.361950      54         768
9           1  0.150833  0.150888  0.482917   0.223267      41        1280

    cnt
0   985
1   801
2  1349
3  1562
4  1600
5  1606
6  1510
7   959
8   822
9  1321

### **[실습]**
아래 코드의 차이점이 무엇인지 실행해보고 알아보십시오.

* df_bike.iloc[-10:]
* df_bike.iloc[:-10]

In [9]:
# 행 추출

print(df_bike.iloc[-10:]) # 마지막 10개행
print(df_bike.iloc[:-10]) # 마지막 10개 행을 제외한 모든 행

     instant      dteday  season  yr  mnth  holiday  weekday  workingday  \
721      722  2012-12-22       1   1    12        0        6           0
722      723  2012-12-23       1   1    12        0        0           0
723      724  2012-12-24       1   1    12        0        1           1
724      725  2012-12-25       1   1    12        1        2           0
725      726  2012-12-26       1   1    12        0        3           1
726      727  2012-12-27       1   1    12        0        4           1
727      728  2012-12-28       1   1    12        0        5           1
728      729  2012-12-29       1   1    12        0        6           0
729      730  2012-12-30       1   1    12        0        0           0
730      731  2012-12-31       1   1    12        0        1           1

     weathersit      temp     atemp       hum  windspeed  casual  registered  \
721           1  0.265833  0.236113  0.441250   0.407346     205        1544
722           1  0.245833  0.259471  0.515417   0.133083     408        1379
723           2  0.231304  0.258900  0.791304   0.077230     174         746
724           2  0.291304  0.294465  0.734783   0.168726     440         573
725           3  0.243333  0.220333  0.823333   0.316546       9         432
726           2  0.254167  0.226642  0.652917   0.350133     247        1867
727           2  0.253333  0.255046  0.590000   0.155471     644        2451
728           2  0.253333  0.242400  0.752917   0.124383     159        1182
729           1  0.255833  0.231700  0.483333   0.350754     364        1432
730           2  0.215833  0.223487  0.577500   0.154846     439        2290

      cnt
721  1749
722  1787
723   920
724  1013
725   441
726  2114
727  3095
728  1341
729  1796
730  2729
     instant      dteday  season  yr  mnth  holiday  weekday  workingday  \
0          1  2011-01-01       1   0     1        0        6           0
1          2  2011-01-02       1   0     1        0        0           0
2          3  2011-01-03       1   0     1        0        1           1
3          4  2011-01-04       1   0     1        0        2           1
4          5  2011-01-05       1   0     1        0        3           1
..       ...         ...     ...  ..   ...      ...      ...         ...
716      717  2012-12-17       4   1    12        0        1           1
717      718  2012-12-18       4   1    12        0        2           1
718      719  2012-12-19       4   1    12        0        3           1
719      720  2012-12-20       4   1    12        0        4           1
720      721  2012-12-21       1   1    12        0        5           1

     weathersit      temp     atemp       hum  windspeed  casual  registered  \
0             2  0.344167  0.363625  0.805833   0.160446     331         654
1             2  0.363478  0.353739  0.696087   0.248539     131         670
2             1  0.196364  0.189405  0.437273   0.248309     120        1229
3             1  0.200000  0.212122  0.590435   0.160296     108        1454
4             1  0.226957  0.229270  0.436957   0.186900      82        1518
..          ...       ...       ...       ...        ...     ...         ...
716           2  0.393333  0.401500  0.907083   0.098258     212        4373
717           1  0.410833  0.409708  0.666250   0.221404     433        5124
718           1  0.332500  0.342162  0.625417   0.184092     333        4934
719           2  0.330000  0.335217  0.667917   0.132463     314        3814
720           2  0.326667  0.301767  0.556667   0.374383     221        3402

      cnt
0     985
1     801
2    1349
3    1562
4    1600
..    ...
716  4585
717  5557
718  5267
719  4128
720  3623

[721 rows x 16 columns]

### **[실습]**
Cancer 데이터에서 10대 이상, 담배를 피는 경우 데이터를 추출하기 위한 코드를 작성해보세요.

In [10]:
import pandas as pd

# 10대 이상이고 흡연하는 경우 필터링
df_cancer_filtered = df_cancer[(df_cancer['Age'] >= 10) & (df_cancer['Smokes'] == 1)]

# 필터링된 데이터 확인
print("Filtered Data Shape:", df_cancer_filtered.shape)  # 필터링된 데이터 크기 확인
print(df_cancer_filtered.head())  # 상위 5개 데이터 출력

Filtered Data Shape: (123, 16)
    Age  Number.of.sexual.partners  First.sexual.intercourse  \
3    52                          5                        16
6    51                          3                        17
9    44                          3                        15
28   37                          3                        24
32   37                          3                        17

    Num.of.pregnancies  Smokes  Smokes..years.  Hormonal.Contraceptives  \
3                    4       1       37.000000                        1
6                    6       1       34.000000                        0
9                    1       1        1.266973                        0
28                   1       1        3.000000                        0
32                   5       1        1.266973                        1

    Hormonal.Contraceptives..years.  IUD  IUD..years.  STDs  STDs..number.  \
3                               3.0    0          0.0     0              0
6                               0.0    1          7.0     0              0
9                               0.0    0          0.0     0              0
28                              0.0    0          0.0     0              0
32                             10.0    0          0.0     1              1

    STDs..Number.of.diagnosis  STDs..Time.since.first.diagnosis  \
3                           0                                 1
6                           0                                 1
9                           0                                 1
28                          0                                 1
32                          0                                 1

    STDs..Time.since.last.diagnosis  Biopsy
3                                 1       0
6                                 1       1
9                                 1       0
28                                1       0
32                                1       0

### **[실습]**
오른쪽 상단에 있는 Gemini를 이용해서 위의 작업을 수행하기 위한 코드를 작성해보세요.

# **[수업 내용 확인하기]**

### 1) 아래 명령어가 어떤 조건의 데이터 셋을 불러오는지 서술하세요.

df_bike.loc[(df_bike['season']==3) & (df_bike['weekday']>=2)]


### 2) Cancer 데이터에서 30대 이상, 임신 횟수 1번 이상, 담배를 피지 않는 경우 자궁암 발생 환자와 발생하지 않는 환자의 비율을 구하세요.

**1, 2 모두 LMS 과제란에 제출하기 바랍니다.**

In [11]:
# df_bike 데이터프레임에서 season이 3(여름)이고 weekday가 2(화요일) 이상인 데이터를 필터링하는 작업
# 자전거 데이터에서 season은 1 (Winter), 2 (Spring), 3 (Summer), 4 (Fall)로 변환
df_bike.loc[(df_bike['season']==3) & (df_bike['weekday']>=2)]

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
171,172,2011-06-21,3,0,6,0,2,1,2,0.680833,0.637646,0.770417,0.171025,774,4061,4835
172,173,2011-06-22,3,0,6,0,3,1,1,0.733333,0.693829,0.707500,0.172262,661,3846,4507
173,174,2011-06-23,3,0,6,0,4,1,2,0.728333,0.693833,0.703333,0.238804,746,4044,4790
174,175,2011-06-24,3,0,6,0,5,1,1,0.724167,0.656583,0.573333,0.222025,969,4022,4991
175,176,2011-06-25,3,0,6,0,6,0,1,0.695000,0.643313,0.483333,0.209571,1782,3420,5202
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
626,627,2012-09-18,3,1,9,0,2,1,2,0.623333,0.565067,0.872500,0.357587,371,3702,4073
627,628,2012-09-19,3,1,9,0,3,1,1,0.552500,0.540404,0.536667,0.215175,788,6803,7591
628,629,2012-09-20,3,1,9,0,4,1,1,0.546667,0.532192,0.618333,0.118167,939,6781,7720
629,630,2012-09-21,3,1,9,0,5,1,1,0.599167,0.571971,0.668750,0.154229,1250,6917,8167
630,631,2012-09-22,3,1,9,0,6,0,1,0.650000,0.610488,0.646667,0.283583,2512,5883,8395

In [12]:
import pandas as pd

# 데이터 불러오기 (파일 경로를 사용자 환경에 맞게 수정 필요)
# df_cancer = pd.read_csv("cancer.csv")

# 필터링 조건: 30대 이상, 임신 횟수 1번 이상, 흡연하지 않는 경우
df_filtered = df_cancer[(df_cancer['Age'] >= 30) & 
                        (df_cancer['Num.of.pregnancies'] >= 1) & 
                        (df_cancer['Smokes'] == 0)]

# 자궁암 발생 여부(Biopsy 컬럼 기준) 비율 계산
biopsy_counts = df_filtered['Biopsy'].value_counts(normalize=True) * 100

# 결과 출력
biopsy_counts

# 필터링된 데이터에서 30대 이상, 임신 횟수 1번 이상, 담배를 피지 않는 경우의 자궁암 발생 여부 비율은 다음과 같습니다:

# 자궁암 발생 안 함 (Biopsy = 0)
# 자궁암 발생 (Biopsy = 1)

Biopsy
0    93.043478
1     6.956522
Name: proportion, dtype: float64